language: python
python:
    - 2.7_with_system_site_packages
cache:
    - pip
    - apt
addons:
  apt:
    packages:
      - python-dbus
      - python3-dbus

env:
  global:
install:
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-xml --cover-package=omxplayer tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
