# Container based building is disabled by default, if you explicitly
# state you're not doing any superuser stuff then travis will use a
# container which then allows you to cache things
sudo: false
language: python
python:
    - 2.7
cache: pip
install: 
    - apt-get install python-dbus
    - pip install -r requirements.txt
script: nosetests ./tests
