# Use container based infra
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - dbus
      - libdbus-1-dev
      - libdbus-glib-1-dev

before_install:
  - echo "Python diagnostic Information"
  - pyenv versions
  - pyenv local
  - pyenv global
  - 'which -a python'
  - python --version
  - python-config --includes
  - python-config --libs
  - python-config --ldflags
  - pip --version
  - pip install dbus-python
  - ls -l ~/virtualenv

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
