language: python
python:
    - 2.7_with_system_site_packages
    - 3.2_with_system_site_packages
    - 3.3_with_system_site_packages
    - 3.4_with_system_site_packages
    - 3.5_with_system_site_packages
cache:
    - pip
    - apt
addons:
  apt:
    packages:
      - python-dbus
      - python3-dbus

env:
  global:
install:
  - pip install -r requirements.txt
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
